In [1]:
%reset -f

import numpy as np
pi = np.pi

%run "u_thetaZ_thetaX 函数定义.ipynb"

In [2]:
'''单元刚度矩阵'''
# k = stiffness_grillage(theta, EI, GJ, L, degree=True)
k1 = stiffness_grillage(theta=0 , EI=210e9 , GJ=350e9 , L=2 , degree=True)
k2 = stiffness_grillage(theta=90 , EI=210e9 , GJ=350e9 , L=2 , degree=True)


print(f'k1 = \n{np.round(k1, 9)}')
print(f'k2 = \n{np.round(k2, 9)}')


'''组装总体刚度'''
# 单元的全局刚度矩阵列表
ke_list = [k1, k2]

# 每个单元连接的节点
connectivity = [(1, 2), (2, 3)]

# 总体全局刚度矩阵
K = assemble_K_grillage(ke_list, connectivity, n_nodes=3, numbering="one")

print(f'K = \n{np.round(K, 9)}')

'''边界条件'''
# 位移边界条件
disp_bc = {
    dof_grillage(1, "v"): 0.0,
    dof_grillage(1, "theta_z"): 0.0,
    dof_grillage(1, "theta_x"): 0.0,
    
    dof_grillage(3, "v"): 0.0,
    dof_grillage(3, "theta_z"): 0.0,
    dof_grillage(3, "theta_x"): 0.0
}

# 受力边界条件
force_bc = {
    dof_grillage(2, "v"): -10000,
    dof_grillage(2, "theta_z"): 15000,
    dof_grillage(2, "theta_x"): 15000,

}

'''求解'''
d, reaction, free_dofs, fixed_dofs = solve_structure(
    K,
    force_bc=force_bc,
    disp_bc=disp_bc
)

print("d =")
print(np.round(d, 9))

print("reaction =")
print(np.round(reaction, 9))

k1 = 
[[ 3.15e+11  3.15e+11  0.00e+00 -3.15e+11  3.15e+11  0.00e+00]
 [ 3.15e+11  4.20e+11  0.00e+00 -3.15e+11  2.10e+11  0.00e+00]
 [ 0.00e+00  0.00e+00  1.75e+11  0.00e+00  0.00e+00 -1.75e+11]
 [-3.15e+11 -3.15e+11  0.00e+00  3.15e+11 -3.15e+11  0.00e+00]
 [ 3.15e+11  2.10e+11  0.00e+00 -3.15e+11  4.20e+11  0.00e+00]
 [ 0.00e+00  0.00e+00 -1.75e+11  0.00e+00  0.00e+00  1.75e+11]]
k2 = 
[[ 3.1500e+11  1.9288e-05  3.1500e+11 -3.1500e+11  1.9288e-05  3.1500e+11]
 [ 1.9288e-05  1.7500e+11  1.5002e-05 -1.9288e-05 -1.7500e+11  2.3574e-05]
 [ 3.1500e+11  1.5002e-05  4.2000e+11 -3.1500e+11  2.3574e-05  2.1000e+11]
 [-3.1500e+11 -1.9288e-05 -3.1500e+11  3.1500e+11 -1.9288e-05 -3.1500e+11]
 [ 1.9288e-05 -1.7500e+11  2.3574e-05 -1.9288e-05  1.7500e+11  1.5002e-05]
 [ 3.1500e+11  2.3574e-05  2.1000e+11 -3.1500e+11  1.5002e-05  4.2000e+11]]
K = 
[[ 3.1500e+11  3.1500e+11  0.0000e+00 -3.1500e+11  3.1500e+11  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00]
 [ 3.1500e+11  4.2000e+11  0.0000e+00 -3